name: Nightlies
on:
  push:
    branches:
      - master
      - actions
  pull_request:
    branches:
      - master
      - actions
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    strategy:
      matrix:
        branch: [devel, version-1-0]
        target:
          - android-arm64
          - linux-armv6
          - linux-armv7
          - linux-armv7a
          - linux-arm64
          - linux-32
          - linux-64
          - macos-64
          - windows-32
          - windows-64
        include:
          - target: android-arm64
            os: ubuntu-18.04
            osvar: android
          - target: linux-armv6
            os: ubuntu-18.04
            osvar: linux
          - target: linux-armv7
            os: ubuntu-18.04
            osvar: linux
          - target: linux-armv7a
            os: ubuntu-18.04
            osvar: linux
          - target: linux-arm64
            os: ubuntu-18.04
            osvar: linux
          - target: linux-32
            os: ubuntu-18.04
            osvar: linux
          - target: linux-64
            os: ubuntu-18.04
            osvar: linux
          - target: macos-64
            os: macos-10.15
            osvar: osx
          - target: windows-32
            os: windows-2019
            osvar: windows
          - target: windows-64
            os: windows-2019
            osvar: windows
    name: ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    env:
      OSVAR: ${{ matrix.osvar }}
    steps:
      - name: Setup environment
        shell: bash
        run: |
          ARCH='${{ matrix.target }}'
          ARCH=${ARCH%%*-}
          echo "ARCH: $ARCH"
          echo "::set-env name=ARCH::$ARCH"

      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout Nim
        uses: actions/checkout@v2
        with:
          repository: nim-lang/Nim
          ref: ${{ matrix.branch }}
          path: nim
      - name: Checkout csources
        uses: actions/checkout@v2
        with:
          repository: nim-lang/csources
          path: nim/csources

      - name: Install node.js
        uses: actions/setup-node@v1
        with:
          node-version: 8.x
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo DEBIAN_FRONTEND='noninteractive' apt-fast install \
            libcurl4-openssl-dev libsdl1.2-dev libgc-dev libsfml-dev
      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install boehmgc sfml gnu-tar node
      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        shell: bash
        run: |
          mkdir dist
          curl -L "https://nim-lang.org/download/mingw$ARCH-6.3.0.7z" -o "dist/mingw${ARCH}.7z"
          7z x "dist/mingw$ARCH.7z" -odist
