name: Nightlies
on:
  push:
    branches:
      - master
      - actions
  pull_request:
    branches:
      - master
      - actions
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    strategy:
      matrix:
        branch: [devel, version-1-2]
        - target: android
          osarch: arm64
        - target: linux
          osarch: armv6
        - target: linux
          osarch: armv7a
        - target: linux
          osarch: armv7
        - target: linux
          osarch: armv64
        - target: linux
          osarch: 32
        - target: linux
          osarch: 64
        - target: macos
          osarch: 64
        - target: windows
          osarch: 32
        - target: windows
          osarch: 64
        include:
          - target: android
            os: ubuntu-18.04
          - target: linux
            os: ubuntu-18.04
          - target: macos-64
            os: macos-10.15
          - target: windows
            os: windows-2019
    name: '${{ matrix.target }} (${{ matrix.osarch }})'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout Nim
        uses: actions/checkout@v2
        with:
          repository: nim-lang/Nim
          ref: ${{ matrix.branch }}
          path: nim
      - name: Checkout csources
        uses: actions/checkout@v2
        with:
          repository: nim-lang/csources
          path: nim/csources

      - name: Install node.js
        uses: actions/setup-node@v1
        with:
          node-version: 8.x
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo DEBIAN_FRONTEND='noninteractive' apt-fast install -yq \
            libcurl4-openssl-dev libsdl1.2-dev libgc-dev libsfml-dev
      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install boehmgc sfml gnu-tar node
      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        shell: bash
        run: |
          mkdir dist
          curl -L "https://nim-lang.org/download/mingw$ARCH-6.3.0.7z" -o "dist/mingw${ARCH}.7z"
          7z x "dist/mingw$ARCH.7z" -odist
